services:
  nginx:
    image: scalable-scraper-nginx:ci
    pull_policy: never
    build:
      context: .
      dockerfile: nginx/Dockerfile

  api:
    image: scalable-scraper-api:ci
    pull_policy: never
    build:
      context: ./api

  scraper:
    image: scalable-scraper-scraper:ci
    pull_policy: never
    build:
      context: ./scraper
